apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db
spec:
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: pgo-s3-creds
      repo:
        name: repo1
        s3:
          bucket: 'b4mad-racing-psql'
          endpoint: 'https://192.169.178.22:9000/'
          region: 'ca-central-1'
      # options:
      # - --type=time
      # - --target="2021-06-09 14:15:11-04"
