---
# Source: influxdb/templates/pvc-backup.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb2-backups
  namespace: "b4mad-racing-test"
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-5.5.2
    app.kubernetes.io/instance: influxdb2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: influxdb
spec:
  storageClassName: "synostorage-smb"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
