---
# Source: influxdb/templates/pvc-backup.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb2-backups
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-5.7.2
    app.kubernetes.io/instance: influxdb2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: influxdb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
