---
# Source: influxdb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb2
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-5.7.2
    app.kubernetes.io/instance: influxdb2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: influxdb
  annotations:
automountServiceAccountToken: true
