---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegraf
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: telegraf
spec:
  groups:
    - name: service
      rules:
        - alert: TelegrafServiceDown
          annotations:
            description: "Telegraf {{ $labels.namespace }}/{{ $labels.pod }} is down."
            summary: telegraf is down
          expr: 'up{job="telegraf-metrics",endpoint="metrics"} < 1'
          labels:
            severity: critical
