apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: mosquitto

resources:
  - deployment.yaml
  - services.yaml
  - service_account.yaml
  - secret.sealed.yaml

configMapGenerator:
  - name: mosquitto-config
    files:
      - dynamic-security.json
      - mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
