apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
stringData:
    passwords: ENC[AES256_GCM,data:GyM4LGmE4RNZjRmQi7GUlC7i5wXCnwOOCO+9z/+rOyrc/y+3CduCyFzad37H9CLdM4ssYImNknVsNLDBWUvp1lscahpdpzoYyjlnYoGshVGml0+SxXNurAc+/Df/cyUo3CbUpjkiHeGxXG2W2xjQ7J5xx/PVkn9B9DSvjLFyIYDtcP1hrNiBmmkV2hqyz53IFrTv1kyD0N0Ps8ggMT0PP1hOKaH5+WhWNhnb/90AZllN6hmwwr5ubq9YXuThlyIq6yQc0RBkbQIrg3TLzFKg2MMmW72jhAQy00bjgGyxtI7zvnAGM0No2maS,iv:r3wNYdFyAt2KKno2aOdorLZnf0F+lJfZzPasMpp7ZD8=,tag:qeRwCYGnUIixT1ztNvP59A==,type:str]
    crewchief-username: ENC[AES256_GCM,data:q92u30fjSiWY,iv:rgiwqG/aZfMW6jvsYvLKfd7OJ7sMF8AigK89OqOZeyQ=,tag:wA6YGHv7PE7ey1a9B5yzQA==,type:str]
    crewchief-password: ENC[AES256_GCM,data:EhWtVUzznnqY,iv:MhUc29KASmKE5K/yyG8P+sjhdyNGalBdU/jowbk2HOQ=,tag:w1CHc2C0EoVbB9yRmTGHXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-04T15:06:02Z"
    mac: ENC[AES256_GCM,data:5LDL4Ne8A/zWpKX4tuHDhSZM94ZIU7+VYl1QOOoCDpRtwwM+Gu/SNxyqJd7PwbrUgHH/RoDagBNlnGBNifdGXE7BydnCb4+zXGafMJ78KutYpZp3f9rJBMhUd2vjYfZG+1OpcvnlQSRhQXoEMDOkvUtIn2t4E0XZeJh3caFTEeo=,iv:rLijUjY023VmhPWxrhuYS1VAZUMRLOwtHCLpkZ508gY=,tag:/IQGd8luH9fBFF7U+8W2WQ==,type:str]
    pgp:
        - created_at: "2022-10-04T12:48:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAAv8No3wehJGVxMGbzSGBm7xEgEDQxCzMxkjYdHukWvE+l
            gLg1UVYzpxbjMuqn78XtN8f1GdO+WaoFuOJWDv8NSuOBcVQk0TEG+l0FZjzL/9wu
            ACdpxpTa4LjFqAN8mL/Kfw4y35T6LOldnUA+yeAvMGHksr9tH/60fYOT9IE0RjeM
            q6HLvNXgzFXjZJAgvEBMN9cv0nDfS7ynM+ya7gLZMon1GFWVsalZJGKQE0Eycxnt
            4xiC9sc31H8fC6W/YKEUtLT9rc1i1aO6aIb0in73uxvU6aqvhK/JsxL1B2i1yUDq
            KNsDX9yog21n5M/AyJUn5LYmStnJxWTbUVTy8v2Od61dQGbRdNG8CVkR7kovjhnf
            9bqoksr6e/7nORSYX6YwvPgW77/126H9qGMEVmz7dZeUR4usCDQRzLNzRKuUSPYd
            cslNvHKXTEqU94GBiCeG2/A3TTCiTQRS0JmuZSdwsxMgnSveyecPt/Jnpo65OeD9
            QGqK2AKtLw5J8TQa5+WcUAmNSBM4TedkPBIecOzp70Kxgg5JGbE1A31q6CQhqOWA
            9rPIzEtXhM+99Qs8YPw507gBmt6uv47Y5D8qgdBlUxoysilv9abzTmrG2i0rWPx8
            j1+iwWKLCOJmjb93Kav0oTPo79sEEmTueDX47vuaoZsJThYG8sIWZVPUYMqIWUrS
            XgFo32pht6PNeDRzkZG04VOvA0OY5C73z1quR0Etk7GJdGtfOJidvykKqSLYbVyS
            hdCfRupThR/3OyboRGSSVzfF7AMMcy0YrWwECjW6RdlJunDDecBHMMYVnLU2eF8=
            =eSAK
            -----END PGP MESSAGE-----
          fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
        - created_at: "2022-10-04T12:48:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQgAl8+pat25GYF3iQWvk8FQ8EYIaXf4NuQt5opsynWz+dmk
            sPIA6vNKHbaKgn/FOG+t5+5YmYO0w8b6YLtkcWwuULCmD/n9Dtp59yCeeug9xAiV
            9vnc9qDfCXitpr5Mbli0SKg4k3d/NwlzMvEr5RG7nAdwLhdFPjC91WmNyqweJ/N6
            duHcYY5DGnThcQV6jCrJKckgjFaNa4faE6aFy3kn+kXH+B4zUunKXedlhAhVu/m3
            Jo0dE2NqMDBuvYELvyIZT6hNGeSgwTGCAlYx383RjifWOD/YLzr0Qv1pXTjgCI7G
            KbdSs+OBc4pxr3iuDBM92YqLVLi24u0RhL62FuzDa9JeAaX6Btcg1ttF0RRdaxhQ
            tVMibsw6qxdbKNQIZw3JzM2bQu4z8yORgWclw8ZRAN7mduNtgRkN3cduGPx8Qb8Y
            j4/BGywTtXV8+TbsCFgXqhbIshKHoZKj7KPWF2D1EA==
            =sKQQ
            -----END PGP MESSAGE-----
          fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
        - created_at: "2022-10-04T12:48:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgApsHa6umk1BogdWup8BXLM6nV5EI3I/2d+Qq3Z3OrftXw
            mt1eyuvJB+HXC+uufAc97POzaOZZn4fkyN/xreFfzOYkHDs/0Ijt6nB7zVz+zXXR
            KScV9pugypiYTn/uR+nqyTCazYUyKLIWyHRi+VRRbTVxEe4iImoS/Wt6LXsgB/US
            v4mvn6qPWGpqwcdx/s+VGIoKwe7WXmwywiTKKAALfof2ZNIQfZ7Ii3kK9srb8wpF
            +UB82vKPuanbg7EPFUea71rj/B6JddWROWmVSq+6DC1YoBz3oUbMa/k26FXJUYNi
            mCfLRGjTUzD5vEesZ+tw0uryQlXWbLZthXtca22FmdJeATuYXB3uP0EvJRBEHSfz
            r5JsKI9an8ypiPY+F7rbd26huMI4E7Qc+73k5rpDauWC/nB6ahlkbY97cardLmkC
            w8riqu3brticBEoUq0dI34XxLbo2Kzb7eZAVHTvTRQ==
            =1Bco
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2022-10-04T12:48:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//Sa3VKjCp9kR/kcIUFaKIH7CsNLSNQpEh2DgSCn+S1YyG
            vJb17hz8vUnAkxiLmqMChmM6vB4/WeFsojiB22S4a/4fEq9EeGSXBtYIDFFF+Ip3
            FcjvZvIXaCFDovbJ6Rzm8iY5CUqY/lkirVdCsQLaKs6gNcAJvZ8erKAGXm9mntCV
            B4nHIYk9/Izt8jC6czwHBdNNteh0cCtYOp9nOJ6R16rzxP7YtqqNYCAl+sqfkhJc
            HCgP9LobAWgv8CTBO3JTVQoi9CW+VZBladnWRkn6Rc8U/MyaePiFEa8Fl8VCAEUu
            XezwknMfthBHDqQL4oPhWBIWIIjtjE1eFSNNLjMItuLcbrr01v/Q0pcxD7LNw3GN
            14R4ssXOFDAmLT3DWDMdDFTGLQ/B4y3IcMeVccoCFzKyEaXXFwvSfJk0u+5kb0K2
            y54I2+Oh95sKdsDVZ6w3NXMdu9cdUVQNeltpKpTJ7n8YWdrDBitPtaErrdCfyPYg
            ky6YNGteMJbJ1Uo2jtdsWiaUZ5Pdmxv//FJkbJAaNqGfSAq0BusurxVGvQUT2lti
            3eWk2zPUgcE9zAO+sSmZFwYX2RUpRSdyBkUy/IFhYDaUTGKEAbXNfkp/CjyaE2K2
            FdMsPrMRct3dm3Qd64r2IY13mY7RoJ2rUhLomdCno1iIvND+JdO8qo8X8qFt3MzS
            XgFhQHihevFV4aNjFSFpBD6FyaFQz2QfgYAJG3NvM5mXpXDbuJwZanz7Zc5Cb+W+
            R+U0QAB2WOKrGvLjZ9SkRObAX9hJGEuo6QEzF5zqdUMIyx4hxUbas2/DF0yNgZQ=
            =lzBH
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.2
