kind: Service
apiVersion: v1
metadata:
  name: mosquitto-mqtt
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      nodePort: 31880
      port: 1883
      protocol: TCP
      targetPort: 1883
