apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/paddock/
  - ../../../base/paddock/metrics-exporter/

patches:
  - target:
      kind: Ingress
      name: paddock
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock-nostromo-stage.b4mad.racing

  - target:
      kind: Ingress
      name: paddock-metrics-exporter
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock-metrics-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock-metrics-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock-metrics-nostromo-stage.b4mad.racing

  - target:
      kind: DeploymentConfig
      name: paddock
    patch: |-
      - op: remove
        path: /spec/triggers
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOST
          value: paddock-nostromo-stage.b4mad.racing
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PROMETHEUS_MULTIPROC_DIR
          value: /tmp/django-metrics
