apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/paddock

patches:
  - target:
      kind: ServiceMonitor
      name: paddock
    patch: |
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: b4mad-racing-stage

  - target:
      kind: Ingress
      name: paddock
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock-nostromo-stage.b4mad.racing

  - target:
      kind: DeploymentConfig
      name: paddock
    patch: |-
      - op: remove
        path: /spec/triggers

  - target:
      kind: DeploymentConfig
      name: paddock
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOST
          value: paddock-nostromo-stage.b4mad.racing
