apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mosquitto

  - mosquitto-exporter.yaml
  - mosquitto-password.yaml

patches:
  - target:
      kind: Deployment
      name: mosquitto
    patch: |-
      - op: add
        path: /spec/template/spec/containers/-
        value:
          name: mosquitto-exporter
          image: quay.io/b4mad/mosquitto-exporter@sha256:abe94175914684b88ca9ec9c256b4fa8a067e5bd3cec4cf9ded31586b386d1b2
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
          ports:
            - name: metrics
              containerPort: 9234
              protocol: TCP
          envFrom:
            - prefix: MQTT_
              secretRef:
                name: mosquitto-exporter
