{
 "title": "B4mad Racing CrewChief Landingpage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SessionTypeName",
    "label": "SessionTypeName",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"SessionTypeName\")\n"
   },
   {
    "name": "User",
    "label": "User",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"user\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "#B4mad Racing",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# [#B4mad racing](https://b4mad.racing) 🏎\n\n_Community-driven SimRacing data collection and analysis_\n\nEnable MQTT in [CrewChief](https://thecrewchief.org/) 👨‍🚀 <br/> \nContribute at [github/b4mad/racing](https://github.com/b4mad/racing) 🐙"
   }
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"SessionId\",\n    start: -10y\n) |> count()\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"user\",\n    start: -10y\n)\n"
    }
   ]
  },
  {
   "title": "GameName",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"GameName\",\n    start: -10y\n)\n"
    }
   ]
  },
  {
   "title": "TrackCode",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"TrackCode\",\n    start: -10y\n)\n"
    }
   ]
  },
  {
   "title": "CarModel",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"CarModel\",\n    start: -10y\n)\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"user\",\n    start: -10y\n) |> count()\n"
    }
   ]
  },
  {
   "title": "Recent Sessions",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentLapTime\" )\n  |> keep(columns: [\"GameName\", \"user\", \"CarModel\", \"TrackCode\", \"SessionId\", \"SessionTypeName\", \"_time\", \"_value\"])\n  |> last()\n  |> group(columns: [])\n"
    }
   ]
  }
 ]
}