{
 "title": "B4mad Racing CrewChief Landingpage",
 "tags": [
  "B4Mad",
  "1st_Level"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SessionTypeName",
    "label": "SessionTypeName",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"SessionTypeName\")\n"
   },
   {
    "name": "User",
    "label": "User",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"user\")\n"
   },
   { "name": "RegEX", "query": "/^([a-zA-Z0-9ü]+)/" },
   { "name": "Domain", "query": "https://pitwall.b4mad.racing" },
   {
    "name": "Extended",
    "query": "e12c7ccb-ff51-4525-b5da-0d783a1019ef/b4mad-session-details"
   },
   {
    "name": "Standard",
    "query": "6d57246de74745198b3385f5e446e81cf7127b47/session"
   },
   {
    "name": "Driver",
    "query": "9f21413861900279156aea9e866fdf7adc8629c5/driver"
   },
   {
    "name": "Track",
    "query": "c726e9a2-350c-459d-aa40-2035073f5035/track-standings"
   },
   { "name": "DS_RACING", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# [#B4mad racing](https://b4mad.racing) 🏎\n\n_Community-driven SimRacing data collection and analysis_\n\nEnable MQTT in [CrewChief](https://thecrewchief.org/) 👨‍🚀 <br/> \nContribute at [github/b4mad/racing](https://github.com/b4mad/racing) 🐙<br />\nJoin our [Discord](https://discord.com/invite/MaUQuSGSbJ) and say hello 👋<br />\nJoin us and ask about Coach AI and Extended Telemetry"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"SessionId\",\n) |> count()\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"user\",\n\n)\n"
    }
   ]
  },
  {
   "title": "GameName",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"GameName\",\n  \n)\n"
    }
   ]
  },
  {
   "title": "TrackCode",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"strings\"\nimport \"regexp\"\nregex = ${RegEX}\n\ndata  = schema.tagValues(\n    bucket: \"racing\",\n    tag: \"TrackCode\",\n    )\n\nsingle =data\n |> map(fn: (r) => ({r with trackShort: regexp.findString(v: r._value, r: regex)}))\n |> yield() "
    }
   ]
  },
  {
   "title": "CarModel",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"CarModel\",\n    \n)\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"user\",\n    start: -10y\n) |> count()\n"
    }
   ]
  },
  {
   "title": "Recent Sessions",
   "type": "table",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"regexp\"\nregex = ${RegEX}\n\ndata = from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentLapTime\" )\n\nValid = data\n  |> keep(columns: [\"GameName\", \"user\", \"CarModel\", \"TrackCode\", \"SessionId\", \"SessionTypeName\", \"_time\", \"_value\"])\n  |> last()\n  |> group(columns: [])\n  |> map(fn: (r) => ({r with SessionId: r.SessionId,\n    Check: \n      if r._value > 1 then \"Valid\"\n      else \"Invalid\",\n    TrackCode: strings.toLower(v: r.TrackCode),  \n    trackShort: regexp.findString(v: r.TrackCode, r: regex)  \n    }))\n\nStart = data\n  |> first(column: \"_time\")\n  |> map(fn: (r) => ({r with Start:  r._time\n  }))\n  |> group()  \n  |> keep(columns: [\"SessionId\", \"Start\"])\n\nStop = data\n  |> last(column: \"_time\")\n  |> map(fn: (r) => ({r with Stop:  r._time}))\n  |> group()  \n  |> keep(columns: [\"SessionId\",\"Stop\"])\n\nt1 = join(tables: {Valid: Valid, Start: Start,}, on: [\"SessionId\"] )\n  |> sort(columns: [\"_time\"], desc: false)\n  |> group(columns: [])\n\nt2 = join(tables: {t1: t1, Stop: Stop,}, on: [\"SessionId\"] )\n  |> sort(columns: [\"_time\"], desc: false)\n  |> group(columns: [])\n\n\n   |> yield() \n"
    },
    {
     "query": "data = from(bucket: \"racing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /Session_Type|Rpms/ )\r\n \r\n  |> last()\r\n  |> group(columns: [])\r\n\r\nValid = data\r\n  |> map(fn: (r) => ({r with SessionId: r.SessionId,\r\n    _value: \r\n      if r._field == \"Session_Type\" then \"${Extended}\"\r\n      else \"${Standard}\"\r\n    }))\r\n  |> keep(columns: [\"SessionId\",\"_value\"])  \r\n  |> rename(columns: {_value: \"Data\"})\r\n  |> group()    \r\n   |> yield() \r\n"
    }
   ]
  }
 ]
}