apiVersion: batch/v1
kind: CronJob
metadata:
  name: analyze
  namespace: b4mad-racing
  # image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"paddock:latest"},"fieldPath":"spec.jobTemplate.spec.template.spec.containers[?(@.name==\"analyze\")].image"}]'
spec:
  # run the analyze job an hour after the psql backup job
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  selector: {}
  jobTemplate:
    spec:
      template:
        metadata:
          name: analyze
        spec:
          containers:
            - env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: db-pguser-paddock
                      key: host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: db-pguser-paddock
                      key: port
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-pguser-paddock
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-pguser-paddock
                      key: password
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: db-pguser-paddock
                      key: dbname
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                    - ALL
              envFrom:
                - secretRef:
                    name: paddock-settings
              image: paddock:latest
              imagePullPolicy: Always
              name: analyze
              command: ["/bin/sh", "-c"]
              args:
                - python /opt/app-root/src/manage.py analyze --copy-influx
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: 100m
                  memory: 256Mi
          restartPolicy: Never
