presubmits:
  - name: kustomize-build
    decorate: true
    max_concurrency: 1
    skip_if_only_changed: "^docs/|\\.md$|^(OWNERS|LICENSE)$|^\\."
    skip_report: false
    context: op1st/prow/kustomize-build
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:latest
          command:
            - "test-kustomize-build"

  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
