presubmits:
  - name: kustomize-build
    decorate: true
    max_concurrency: 1
    skip_if_only_changed: "^docs/|\\.md$|^(OWNERS|LICENSE)$|^\\."
    skip_report: false
    context: op1st/prow/kustomize-build
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:latest
          command:
            - "test-kustomize-build"
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
  - name: e2e-telemetry
    decorate: true
    skip_report: false
    always_run: true
    context: b4mad-racing/e2e/telemetry
    spec:
      containers:
        - image: quay.io/fedora/python-310@sha256:6875e96d2b8f6897e26d578c75e5a0c8efcdbe6a492f22448ff48a98a6d7d2ae
          command:
            - components/paddock/e2e-test.sh
          env:
            - name: SECRET_KEY
              value: abcd1ac34873c54e158d38e7f1283977f202abcd
