host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: components

runtime_environments:
  - name: paddock
    operating_system:
      name: fedora
      version: "35"
    python_version: "3.10"
    recommendation_type: latest
  - name: pitcrew
    operating_system:
      name: ubi
      version: "9"
    python_version: "3.9"
    recommendation_type: latest
  - name: notebooks
    operating_system:
      name: ubi
      version: "9"
    python_version: "3.9"

# https://thoth-station.ninja/docs/developers/kebechet/managers.html#available-managers
managers:
  - name: info
    configuration:
      enabled: false
  - name: label-bot
    configuration:
      enabled: false
  - name: pipfile-requirements
    configuration:
      enabled: false
  - name: thoth-advise
    configuration:
      enabled: false
  - name: thoth-provenance
    configuration:
      enabled: false
  - name: update
    configuration:
      enabled: false
  - name: version
    configuration:
      enabled: false
