host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: analysis
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.9"
    recommendation_type: latest

managers:
  - name: thoth-advise
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
      changelog_smart: true
