FROM quay.io/fedora/python-310@sha256:6875e96d2b8f6897e26d578c75e5a0c8efcdbe6a492f22448ff48a98a6d7d2ae

LABEL \
    org.opencontainers.image.source=https://github.com/b4mad/racing \
    org.opencontainers.image.description="This is the #B4mad Racing Paddock component" \
    org.opencontainers.image.licenses="GPL-3.0-or-later" \
    org.opencontainers.image.base.name="quay.io/fedora/python-310"

ENV \
    DISABLE_SETUP_PY_PROCESSING=1 \
    DISABLE_PYPROJECT_TOML_PROCESSING=1 \
    ENABLE_MICROPIPENV=1

USER 0
ADD . /tmp/src
RUN /usr/bin/fix-permissions /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

CMD /usr/libexec/s2i/run
