FROM quay.io/thoth-station/s2i-thoth-f35-py310:v0.35.1

USER 0
ADD . /tmp/src
RUN /usr/bin/fix-permissions /tmp/src
USER 1001

# Thoth Knowledgebase is lacking some packages, lets try using it later
ENV THOTH_OFF=1

RUN /usr/libexec/s2i/assemble

# https://muafzal.medium.com/creating-django-web-app-in-red-hat-openshift-bae007bfaaff
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
