apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/grafana-v5

generatorOptions:
  disableNameSuffixHash: true

patches:
  # - target:
  #     kind: GrafanaDatasource
  #     name: racing
  #   patch: |-
  #     - op: replace
  #       path: /spec/datasource/url
  #       value: http://influxdb2.b4mad-racing.svc.cluster.local:8086
  - target:
      kind: Ingress
      name: grafana
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pitwall-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pitwall-nostromo-stage.b4mad.racing
