apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - influxdb2/influxdb/templates/configmap-backup.yaml
  - influxdb2/influxdb/templates/cronjob-backup.yaml
  - influxdb2/influxdb/templates/deployment.yaml
  - influxdb2/influxdb/templates/pvc-backup.yaml
  - influxdb2/influxdb/templates/pvc.yaml
  - influxdb2/influxdb/templates/service.yaml
  - influxdb2/influxdb/templates/serviceaccount.yaml
  - influx-config.yaml
  - influx-vars.yaml
  - monitoring_alerting.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment.yaml
  - cronjob-backup.yaml
