---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb2
spec:
  endpoints:
    - interval: 15s
      port: http
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: influxdb
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: influxdb2
spec:
  groups:
    - name: InfluxDB2PersistentVolumes
      rules:
        - alert: InfluxDB2PersistentVolumeFull
          annotations:
            description: InfluxDB2 data volume is full.
            summary: InfluxDB2 data volume is full.
          expr: 'kubelet_volume_stats_available_bytes{job="kubelet",persistentvolumeclaim="influxdb2"} / kubelet_volume_stats_capacity_bytes{job="kubelet",persistentvolumeclaim="influxdb2"} < 0.2'
          labels:
            severity: critical
        # - alert: influxdb2-backup
        #   annotations:
        #     description: InfluxDB2 backup volume is full.
        #     summary: InfluxDB2 backup volume is full.
        #   expr: 'kubelet_volume_stats_available_bytes{job="kubelet",persistentvolumeclaim="influxdb2"} / kubelet_volume_stats_capacity_bytes{job="kubelet",persistentvolumeclaim="influxdb2"} < 0.2'
        #   labels:
        #     severity: critical
    - name: BackupAlertRules
      rules:
        - alert: InfluxDB2BackupTimeout
          expr: time() - max( kube_job_status_start_time * ON(job_name) GROUP_RIGHT() kube_job_labels{job_name=~"influxdb2-backup.*"} * ON(job_name) GROUP_RIGHT() label_replace(kube_pod_labels, "job_name", "$1", "label_job_name", "(.*)") * ON(pod) GROUP_RIGHT() kube_pod_status_phase{job="kube-state-metrics",phase=~"Succeeded"}) BY (job_name,label_postgres_operator_crunchydata_com_pgbackrest_cronjob) > 86400
          labels:
            severity: critical
          for: 10m
          annotations:
            message: "Backup job {{ $labels.job_name }} has NOT been running for more than 24 hours."
        - alert: InfluxDB2FailedBackupPods
          expr: kube_pod_status_phase{phase="Failed"} * ON(pod) GROUP_RIGHT() kube_pod_labels{label_job_name=~"influxdb2-backup-.*"} > 0
          labels:
            severity: critical
          for: 10m
          annotations:
            message: "Backup job {{ $labels.job_name }} has NOT been running for more than 24 hours."
