{
 "title": "B4mad Racing Details CrewChief",
 "time": { "from": "2022-09-02T13:32:24.582Z", "to": "2022-09-02T13:37:16.632Z" },
 "templating": {
  "list": [
   {
    "name": "SessionId",
    "label": "SessionId",
    "query": "49080d03-6f93-47fb-8602-be3dadab2567"
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Sessions",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionId\"] == \"${SessionId}\")\n  |> keep(columns: [\"GameName\", \"user\", \"CarModel\", \"TrackCode\", \"SessionId\", \"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: false)\n  |> first()\n  |> group(columns: [])\n  |> drop(columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionId\"] == \"${SessionId}\")\n  |> filter(fn: (r) => (r[\"_field\"] == \"Gear\" or r[\"_field\"] == \"Brake\" or r[\"_field\"] == \"SteeringAngle\" or r[\"_field\"] == \"Clutch\" or r[\"_field\"] == \"Throttle\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Distance Meters",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionId\"] == \"${SessionId}\")\n  |> filter(fn: (r) => (r[\"_field\"] == \"DistanceRoundTrack\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "SpeedKmh",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionId\"] == \"${SessionId}\")\n  |> filter(fn: (r) => (r[\"_field\"] == \"SpeedMs\"))\n  |> map(fn: (r) => ({ r with _value: r._value * 3.6 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "RPMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionId\"] == \"${SessionId}\")\n  |> filter(fn: (r) => (r[\"_field\"] == \"Rpms\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Brake on track",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "brake = from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Brake\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nx = from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TrackPositionPercent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\njoin(tables: {brake: brake, x: x}, on: [\"_time\"] )\n  |> keep(columns: [\"_value_brake\", \"_value_x\"])\n  |> sort(columns: [\"_value_x\"], desc: false)\n\n"
    }
   ]
  }
 ]
}