{
 "title": "B4mad Racing CrewChief",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SessionTypeName",
    "label": "SessionTypeName",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"SessionTypeName\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"SessionId\")\n |> count()"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"UserId\")\n |> count()"
    }
   ]
  },
  {
   "title": "GameName",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"GameName\")\n"
    }
   ]
  },
  {
   "title": "TrackCode",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"TrackCode\")\n"
    }
   ]
  },
  {
   "title": "CarModel",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"CarModel\")\n"
    }
   ]
  },
  {
   "title": "Recent Sessions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionTypeName\"] =~ /^${SessionTypeName:regex}$/ )\n  |> keep(columns: [\"GameName\", \"user\", \"CarModel\", \"TrackCode\", \"SessionId\", \"SessionTypeName\", \"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> first()\n  |> group(columns: [])\n  |> drop(columns: [\"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "Laps",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"SessionTypeName\"] =~ /^${SessionTypeName:regex}$/ )\n  |> filter(fn: (r) => (r[\"_field\"] == \"CurrentLap\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  }
 ]
}