apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: b4mad-racing
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAprPKyZkpR0NjbPoKRmKZBmlDV9YttnbUdg2cE/wHdHTAZWD54gjigkdkP64zw9M24+uykZoYhMri9pidcB3J9qF+bmdXY327ipl8BqkfN/Jm4CROl+CfBBwzjBnj7GmR/9zkV2EGHZ43di4RxK/AZCaJ9Vjgv1+2+DH4V8tJLWjrfc+DorLOcvREJTzH0FmU3Q9oFlG7Lh0REjO1A8RK/aB5xFpOeg7JNnHsel7FxX4gPBOhLy6kzdbsxYIe2LRs+V0GDG2A9zPFuDd44Vj9jRcFXdIknrkGgyUuGTYQGItfOH27hhns/BLu6sLza0J+WI3iGUXut0HGEN65YCP+WAI5gsAdiwadj5Guut0ZL2LGbdxcXsAAISBFa8F6SQ+CIntOcGQnxKjoME7qnnYZuJz5T9M7vZPKB4xLp+hMZCvApJjYwYlNBvIksvB7dch1hPBPRXvM4/+pQxrKOn2gwOhYbkZcuJ4sqh2WwDU9YdPNDFP7gsXn8Xd9XhJNIQKfGKOOqMx6q4h/pKZledlYMfQO7ph5KLUOURlB0hsD7+dzwuqANaNa+tdchui6FHWdijpcNVLpss+S1JyB5Dj5MUNlkakK/G3+xCchuN7Jb+6jiBAUaWw8vxIKW7VR4EGSzcUNnKQFCMQgwaOrjc8PfJ7ercs+oSt5kJCjvbfx2rrgJBbck+TWeBkCZIPffXV8RD1xX2VkbmEcf2X2ve3Uv7CiY0A==
    GF_SECURITY_ADMIN_USER: AgBogDcou4EGSXcEccxWi7IjYRMcbKy5JdZnM74YFKB2UVT3ywuDPP4MWBo/co49trhYiHoQor6+4YnIoB/Kzt3JYQRaM3hlYm837xJlOfrRhInBKPQRIJzZTlymTs5Ok/LANS4OasrK7aD+obB2c3jZMBGVvzZr/qJUbHLcjnJVsr3xrR316wHvDAOFeqnIVw6nokOx2vGzgNNMxMzpK0DEDwHSoyOF4oLUTKvFeyPudH3fAfPLfWLB2qr0ED+AjFrZCUvKvOjF0B8Ka97xFnsMA1EHbYM/gA3WKWeGgZcG7P+U8a8W/Yvc7Z8q2XcrcT9uZdLBXVXi8UCdhsTUBYCLdfXkth1cw9WOJ3kBqVL5GUkiM0kCQvALknF3MleQdsUtV/TM4oqzwAx9XYhexp4pkh/JVQ63U9zUGi12pBWu2BucQDYhD0PrAhuGnM2GsRwPNcriuHWSW1Wk4/4tOfbWE7SS5KY6htcSAMelAg0MpKFXISmdFYR6s/PPfUJWDcvIrU0zXX4cKflzIYaK3X1uk4B1iqYnckvJC0QBEPkAz5YAJva3bJB17S/HueXJgMGIHSCHJRnt0rvfqUdEJPSbq6u97gkwYUQtXG14uWwnAyFkD5lUp+RFn9e13pUQdVH/DTEt8jomyJ31nEZr9CfsxxqclS30IoNj7UthtalMHUa5JZHXECyOhQoU9qPE8V78JOOT2Q==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: b4mad-racing
    type: Opaque
