apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: b4mad-racing

namespace: b4mad-racing

resources:
  - namespace.yaml

  - grafana/
  - influxdb/
  - mosquitto/
  - paddock/
  - postgresql/
  - telegraf/

  - secrets/paddock-settings.sealed.yaml
  - secrets/paddock-socialaccounts.yaml
  - secrets/secret.sealed.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock
    newTag: latest
