apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: humans
    app.kubernetes.io/name: b4mad-racing
    app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing
resources:
- namespace.yaml
- ../../base/mosquitto
- influxdb
- ../../base/telegraf
- postgresql
- ../../base/paddock
- ../../base/paddock/cronjobs
- paddock-settings.sealed.yaml
- grafana
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Service
      name: mosquitto-tcp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31883
  - target:
      kind: Route
      name: telemetry
    patch: |-
      - op: replace
        path: /spec/host
        value: telemetry.b4mad.racing
  - target:
      kind: PersistentVolumeClaim
      name: influxdb2
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "80Gi"
  - target:
      kind: Deployment
      name: influxdb2
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "16Gi"
  - target:
      kind: Ingress
      name: influx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: telemetry.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: telemetry.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-telemetry.b4mad.racing
  - target:
      kind: Deployment
      name: telegraf
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
        value: influx-telegraf
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/key
        value: token
  - target:
      kind: DeploymentConfig
      name: paddock
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/memory
        value: 2Gi
  - target:
      kind: Ingress
      name: paddock
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock.b4mad.racing
  - target:
      kind: Ingress
      name: grafana
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pitwall.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pitwall.b4mad.racing
images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock
    newTag: latest
