apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: b4mad-racing

namespace: b4mad-racing

resources:
  - ../../base/mosquitto

  - grafana/
  - influxdb/
  - namespace.yaml
  - paddock/
  - postgresql/
  - telegraf/

  - secrets/paddock-settings.sealed.yaml
  - secrets/paddock-socialaccounts.yaml
  - secrets/secret.sealed.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Service
      name: mosquitto-tcp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31883

images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock
    newTag: latest
