apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgo-reader
  namespace: b4mad-racing-stage
spec:
  encryptedData:
    password: AgCmOc8rgw1QzGaScrjQkv7kC6L5qDrh1E96Ir8xDXhpLqYHk8NRP61EzjOoPk6TBb9wrgeQ4QhGBE/K2WVLo0vlKs9C2HZBHFp7ks706shlbA1iLUnKDURh/p3z/BaKgKGSk7k2lO+l/VXJXCa4PsOkzRUid/CUVRvG8SODp8rQJCfEWzyc21w2YRh3Pjzz0jz0F093leGQV/n7Pdn2YwdONMLOPZxX1pGMhdAjC9ruRn2A7SSNBNUHKMuQWAJMKpTgVLUZ0WFyIARjMkYj4TP5G8N3eaozlFtl3EdX2v53pHF2MzSZ3G9uc96o1lBCLb/n+VuD4Tsa3LbFHOo6wg7nuuBASdYzuVd5L8X6VOt1f1QiBjfiXucoVrlrcWWiTKy90AHBmlbitQRp9grohRxDfU5CSKIY3EfvQC5cLPN8f95t+N/GKslHqwIVwfS97Ra8xrUBI2IqTKXiTObVXat8fUKRnDbvxq9Do5TL44+iu10f43IvYd1g8mPQPZdUG0ubjnWMPr8pVAb6B9Cl1HBUnW7XgsJZbfSm0/hVGmkEypnfeCIji7hRZrXWzAzsJ25UnWFtwvZuIMImGGhckdJpesYHda8j/QuIkr/FgGZZLnfXyIyk463RSw+WFMV3N9xKULQSJtDAd/6lFBZcRLfEEj4nlkhsw7oMspkpy73sndt6iaBAxLnQO8EeXTEnioyfnsOl+g32y/3Fh3a1SV5dKtZSEA==
    user: AgAkmdWyqNkz1ypnkPB8Y6wXzgfwPeVWEGH78KvzOMjZFMeNrnSkhZ0FiBEgsTnU6RjpApMcHUFj0cX/yL3/JsonnlCN0f+F6JgXR84ail/fAaBTJDPUiBeQyZi16f00NgWIs0kbRkoIXi4yfxAhI5dct4qhXeDzPUPb+iLxJs9bFVFzRXrZFGa22uoeDSk6p4LbwNu6iicX9mkRFXKkde6cuBMCU82W8bXNDMtCNTiGI1LXdh1f/AAw2p5bJGvhMmTy+JSuw5W9rEWhK7JXV4pAoBB+UvgsFScQOWkeLaqyaROVkL+iOvbbzHJ1BbXkmTV3ANB5YEsSqX0oWPB1UoqczfA90Xh9awQUv/WRLIqdjgm1xSzf+v4db6rqxv2ePMowZ/tV/8BSG5auW3cX52dNeUaTDaG5tGimt6+9JCpaTGzLKEF958EfZEWXGYpH2MI1zn31tpFvpYcJ2tHv8mRBRAjSPdTYL/zEd66Hn1MGsnxZ9zMNMe/S8mpAE4LXyjaQQXpx8njl9OHLnEff1b7h+g9jEqN/sNrFH0G9G1zlASy3OMh+SPktJL3nN70NC5pgzHums8bEvr+Ef+QavPUffvlqN8bjqKYhOmeT5lyLlhbLFlkUC6Ih/Kgem1nKhA/RPWHMUue4H8OKZyeRlljhsQxjNRhKpEhBnx1jZD8HrqZfQHeDSR4+wjK1qw5bs30KitBHQ/M=
  template:
    metadata:
      creationTimestamp: null
      name: pgo-reader
      namespace: b4mad-racing-stage
    type: Opaque
