apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/paddock/rebuild

images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock
    newTag: latest
