apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - telegraf/

  - mosquitto/
  - secrets/mosquitto.yaml

  - influxdb/
  - secrets/influxdb2-auth.yaml
  - secrets/influxdb2-backup.yaml

  - postgresql/
  - secrets/pgo-s3-creds.yaml
  - secrets/pgo-reader.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: telegraf
    newTag: "1.27.3"
