apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - telegraf
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: telegraf
    newTag: "1.27.3"
