apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - telegraf
  - ../../base/mosquitto
  - secrets/mosquitto.yaml
  - secrets/influxdb2-auth.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: telegraf
    newTag: "1.27.3"
