apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: b4mad-racing

resources:
  - namespace.yaml

  - rollouts.yaml

  - telegraf/

  - mosquitto/

  - influxdb/
  - secrets/influxdb2-auth.yaml
  - secrets/influxdb2-backup.yaml

  - postgresql/
  - secrets/pgo-s3-creds.yaml
  - secrets/pgo-reader.yaml

  - grafana/
  - secrets/grafana-credentials.yaml
  - secrets/grafana-prometheus-auth.yaml
  - secrets/influxdb2-grafana-auth.yaml

  - paddock/
  - secrets/paddock-settings.yaml
  - secrets/paddock-socialaccounts.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: telegraf
    newTag: "1.28.1"
  - name: paddock
    newName: ghcr.io/b4mad/paddock
    newTag: 96fa853f23dde44156cd04452a60de4775ed04be
  - name: docker.io/eclipse-mosquitto
    newTag: 2.0.17-openssl
