global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

image:
  registry: docker.io
  repository: bitnami/influxdb
  tag: 2.2.0-debian-10-r8
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

architecture: standalone

auth:
  enabled: true
  usePasswordFiles: false
  admin:
    username: admin
    password: KHxFBLKlcfv3
    token: KHxFBLKlcfv3
    org: b4mad
    bucket: racing

  createUserToken: false

influxdb:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 8000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 8Gi

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

serviceAccount:
  enabled: true

metrics:
  enabled: true
  service:
    type: ClusterIP
    port: 9122
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
      prometheus.io/path: "/metrics"
    externalTrafficPolicy: Cluster

  serviceMonitor:
    enabled: true

backup:
  enabled: true
  directory: "/backups"
  retentionDays: 10
  cronjob:
    schedule: "0 2 * * *"
    historyLimit: 1
    podAnnotations: {}
    securityContext:
      enabled: false
  uploadProviders:
    aws:
      enabled: false
      region: "us-east-1"
      existingSecret: "b4mad-racing-influxdb-backup"
      bucketName: "s3://b4mad-racing-smaug/influxdb"
