apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b4mad-racing
spec:
  destination:
    name: phobos
    namespace: b4mad-racing
  project: b4mad
  source:
    path: manifests/env/phobos
    repoURL: https://github.com/b4mad/racing.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=false
