apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-telemetry-test
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: "#B4mad Racing Telemetry e2e test"
spec:
  steps:
    - image: quay.io/fedora/python-310@sha256:430446ef4ea844de1b49e691a9f5da20b2194d6420463dd21e762bacbf713b66
      name: run-e2e-test-in-venv
      workingDir: $(workspaces.source.path)
      command:
        - components/paddock/scripts/e2e-test.sh
      env:
        - name: SECRET_KEY
          value: abcd1ac34873c54e158d38e7f1283977f202abcd
  workspaces:
    - name: source
      mountPath: /workspace/src
      description: >-
        The workspace containing the source code which needs to be released.
