apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: humans
      app.kubernetes.io/name: b4mad-racing
      app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing
resources:
  - ../../../base/postgresql
  - pgo-s3-creds.sealed.yaml
  - pgo-reader.sealed.yaml
patches:
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/service/nodePort
        value: 31884
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 24Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/resources/requests/storage
        value: 100Gi
      - op: add
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/storageClassName
        value: synostorage-smb
      - op: replace
        path: /spec/backups/pgbackrest/global/repo1-type
        value: cifs
      # - op: replace
      #   path: /spec/backups/pgbackrest/repos/0/s3/bucket
      #   value: "b4mad-racing-psql"
      # - op: replace
      #   path: /spec/backups/pgbackrest/repos/2/s3/bucket
      #   value: "b4mad-racing-psql"
