apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: b4mad-racing

namespace: b4mad-racing

resources:
  - ../../../base/postgresql

patches:
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/service/nodePort
        value: 31884
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 26Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/s3/region
        value: eu-central-1
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/s3/endpoint
        value: s3.eu-central-1.amazonaws.com
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/s3/bucket
        value: emea-b4mad-phobos
