apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: humans
    app.kubernetes.io/name: b4mad-racing
    app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing
resources:
- ../../../base/postgresql
- pgo-s3-creds.sealed.yaml
patches:
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/service/nodePort
        value: 31884
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: "8Gi"
      - op: replace
        path: /spec/backups/pgbackrest/repos/1/s3/bucket
        value: "b4mad-racing-psql"
      - op: replace
        path: /spec/backups/pgbackrest/repos/2/s3/bucket
        value: "b4mad-racing-psql"
