apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: b4mad-racing

resources:
  - ../../../base/cloudnative-pg

patches:
  - target:
      kind: Cluster
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/storage/size
        value: 22Gi
  - target:
      kind: Service
      name: postgres
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30432
