apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: b4mad-racing

commonLabels:
  app.kubernetes.io/name: b4mad-racing-test

resources:
  - namespace.yaml
  #- ../../base/mosquitto
  #- ../../base/influxdb
  #- ../../base/telegraf
  - ../../base/postgresql
  - ../../base/paddock
  - paddock-settings.yaml
  #- ../../base/grafana-v5

patches:
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: "8Gi"
      - op: replace
        path: /spec/instances/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/instances/0/resources/limits/memory
        value: "500M"
images:
  - name: paddock
    newName: ghcr.io/b4mad/paddock:6b80b0c352f49d45fefb1c862ea7e7a5c0a490b6
    newTag: latest
