kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: pitwall.b4mad.racing
  to:
    kind: Service
    name: grafana-service
  tls:
    termination:                   edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 3000
  wildcardPolicy: None
