apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: paddock

resources:
  # - deployment_config.yaml
  - deployment.yaml
  - image_stream.yaml
  - monitoring_alerting.yaml
  - service_account.yaml
  - service.yaml
