{
 "title": "User",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SessionTypeName",
    "label": "SessionTypeName",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"SessionTypeName\")\n"
   },
   {
    "name": "user",
    "label": "User",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"user\")\n"
   },
   {
    "name": "GameName",
    "label": "GameName",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"racing\", tag: \"GameName\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "games = [${GameName:doublequote}]\nsession_types = [${SessionTypeName:doublequote}]\nfrom(bucket: \"racing\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r[\"user\"] == \"${user}\")\n  |> keep(columns: [\"SessionId\", \"SessionTypeName\", \"GameName\"])\n  |> limit(n: 1)\n  |> filter(fn: (r) => contains(value: r.GameName, set: games) )\n  |> filter(fn: (r) => contains(value: r.SessionTypeName, set: session_types) )\n  |> group()\n  |> distinct(column: \"SessionId\")\n  |> count()\n\n"
    }
   ]
  },
  {
   "title": "GameName",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"GameName\",\n    predicate: (r) => r[\"user\"] == \"${user}\",\n)"
    }
   ]
  },
  {
   "title": "TrackCode",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"TrackCode\",\n    predicate: (r) => r[\"user\"] == \"${user}\",\n)"
    }
   ]
  },
  {
   "title": "CarModel",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"racing\",\n    tag: \"CarModel\",\n    predicate: (r) => r[\"user\"] == \"${user}\",\n)\n"
    }
   ]
  },
  {
   "title": "Recent Sessions",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "games = [${GameName:doublequote}]\nsession_types = [${SessionTypeName:doublequote}]\n\nfrom(bucket: \"racing\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laps_cc\")\n  |> filter(fn: (r) => r[\"user\"] == \"${user}\")\n  |> keep(columns: [\"GameName\", \"user\", \"CarModel\", \"TrackCode\", \"SessionId\", \"SessionTypeName\", \"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> last()\n  |> group()\n  |> filter(fn: (r) => contains(value: r.GameName, set: games) )\n  |> filter(fn: (r) => contains(value: r.SessionTypeName, set: session_types) )\n  |> sort(columns: [\"End\"], desc: true)\n"
    }
   ]
  }
 ]
}