replicaCount: 1

image:
  repo: "telegraf"
  tag: "1.22-alpine"
  pullPolicy: IfNotPresent

podAnnotations: {}

podLabels: {}

imagePullSecrets: []

## Configure args passed to Telegraf containers
args: []

# The name of a secret in the same kubernetes namespace which contains values to
# be added to the environment (must be manually created)
# This can be useful for auth tokens, etc.

# envFromSecret: "telegraf-tokens"
env:
  - name: HOSTNAME
    value: "telegraf"

resources:
  {}
  # requests:
  #   memory: 128Mi
  #   cpu: 100m
  # limits:
  #   memory: 128Mi
  #   cpu: 100m

service:
  enabled: true
  type: ClusterIP
  annotations: {}

serviceAccount:
  create: true
  name:
  annotations: {}

config:
  agent:
    interval: 1s
    flush_interval: 2s
    debug: false
    quiet: false
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_jitter: "0s"
    precision: ""
    logfile: ""
  outputs:
    - influxdb_v2:
        urls:
          - "http://b4mad-racing-influxdb2.b4mad-racing.svc.cluster.local:8086"
        organization: b4mad
        bucket: racing
        token: KHxFBLKlcfv3
  inputs:
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50
          - 95
          - 99
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000

    - mqtt_consumer:
        username: admin
        password: admin
        data_format: json_v2
        servers:
          - "tcp://mosquitto-ephemeral-tcp:1883"
        topics:
          - racing/+
        topic_parsing:
          - topic: racing/durandom
            tags: _/user
            types:
              user: string
        json_v2:
          - measurement_name: laps
            timestamp_path: time
            timestamp_format: unix_ms
            timestamp_timezone: UTC
            tag:
              - path: userId
                type: text
            field:
              - path: carState.CarCoordinates.0
                rename: world_x
              - path: carState.CarCoordinates.1
                rename: world_z
              - path: carState.CarCoordinates.2
                rename: world_y
            object:
              - path: carState
                timestamp_key: time
                disable_prepend_keys: true
                excluded_keys:
                  - CarCoordinates
                tags:
                  - CarModel
                  - CarClass

metrics:
  health:
    enabled: false
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false

pdb:
  create: true
  minAvailable: 1
