# Generated by Django 3.2.16 on 2022-11-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fastlapsegment",
            name="fast_lap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fast_lap_segments",
                to="telemetry.fastlap",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={
                ("driver", "session_id", "session_type", "game", "car", "track")
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error", models.CharField(max_length=200, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telemetry.driver",
                    ),
                ),
            ],
        ),
    ]
