# Generated by Django 3.2.16 on 2022-11-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_auto_20221128_1323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="id",
        ),
        migrations.AlterField(
            model_name="coach",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="telemetry.driver",
            ),
        ),
    ]
