# Generated by Django 3.2.16 on 2022-11-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_auto_20221128_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coach",
            name="driver",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="telemetry.driver",
            ),
        ),
    ]
