# Generated by Django 3.2.16 on 2022-12-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_fastlap_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="valid",
            field=models.BooleanField(default=False),
        ),
    ]
