# Generated by Django 3.2.16 on 2022-12-04 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0003_auto_20221203_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="end",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
