# Generated by Django 3.2.18 on 2023-02-22 17:36

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_lap_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="fastlap",
            name="data",
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
