# Generated by Django 3.2.16 on 2022-11-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0005_auto_20221128_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="error",
            field=models.CharField(default="", max_length=200),
        ),
    ]
