# Generated by Django 4.2.1 on 2023-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0007_remove_fastlap_lap_lap_fast_lap"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="status",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="coach",
            name="error",
            field=models.TextField(default=""),
        ),
    ]
