# Generated by Django 4.2.1 on 2023-05-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0008_coach_status_alter_coach_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="fast_lap",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coaches", to="telemetry.fastlap"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="track_walk",
            field=models.BooleanField(default=False),
        ),
    ]
