# Generated by Django 4.2.3 on 2023-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0010_alter_fastlap_options_car_created_car_modified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="track_walk",
        ),
        migrations.AddField(
            model_name="coach",
            name="mode",
            field=models.CharField(default="", max_length=64),
        ),
    ]
