# Generated by Django 4.2.3 on 2023-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0011_remove_coach_track_walk_coach_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="mode",
            field=models.CharField(
                choices=[("default", "Default"), ("debug", "Debug")], default="default", max_length=64
            ),
        ),
    ]
