# Generated by Django 4.2.3 on 2023-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0015_landmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="from_cc",
            field=models.BooleanField(default=False),
        ),
    ]
