# Generated by Django 4.2.3 on 2023-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0019_alter_trackguidenote_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackguidenote",
            name="score",
            field=models.CharField(default="", max_length=64),
        ),
    ]
