# Generated by Django 4.2.3 on 2023-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0020_trackguidenote_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackguidenote",
            name="at_start",
            field=models.CharField(default="", max_length=64),
        ),
    ]
