# Generated by Django 4.2.3 on 2023-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0021_trackguidenote_at_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="mode",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("track_guide", "Track Guide"),
                    ("track_guide_app", "Track Guide Application"),
                    ("debug_app", "Debug Application"),
                    ("debug", "Debug"),
                    ("only_brake", "Only Brakepoints"),
                    ("only_brake_debug", "Only Brakepoints (Debug))"),
                ],
                default="default",
                max_length=64,
            ),
        ),
    ]
