# Generated by Django 4.2.5 on 2023-09-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0022_alter_coach_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackguidenote",
            name="at_start",
        ),
        migrations.AddField(
            model_name="trackguidenote",
            name="finish_at",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="trackguidenote",
            name="at",
            field=models.CharField(default="", max_length=64),
        ),
    ]
