# Generated by Django 4.2.5 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0023_remove_trackguidenote_at_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackguidenote",
            name="mode",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="trackguidenote",
            name="sort_key",
            field=models.CharField(default="", max_length=64),
        ),
    ]
