apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: humans
    app.kubernetes.io/name: b4mad-racing-test
    app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing-test
resources:
- namespace.yaml
- ../../base/mosquitto
- influx
- ../../base/telegraf
- postgresql
- ../../base/paddock
- ../../base/grafana-v5
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Service
      name: mosquitto-tcp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31183
  - target:
      kind: Route
      name: telemetry
    patch: |-
      - op: replace
        path: /spec/host
        value: telemetry.test.b4mad.racing
  - target:
      kind: Ingress
      name: paddock
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock.test.b4mad.racing
  - target:
      kind: Ingress
      name: grafana
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pitwall.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pitwall.test.b4mad.racing
images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing-test/paddock
    newTag: latest
