apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: humans
    app.kubernetes.io/name: b4mad-racing-test
    app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing-test
resources:
- namespace.yaml
- ../../base/mosquitto
- ../../base/influxdb
- ../../base/telegraf
- ../../base/postgresql
- ../../base/paddock
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Service
      name: mosquitto-tcp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31183
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/service/nodePort
        value: 31184
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: "1Gi"
      - op: replace
        path: /spec/instances/0/resources/limits/cpu
        value: "50m"
      - op: replace
        path: /spec/instances/0/resources/limits/memory
        value: "50M"
  - target:
      kind: Route
      name: telemetry
    patch: |-
      - op: replace
        path: /spec/host
        value: telemetry.test.b4mad.racing
  - target:
      kind: PersistentVolumeClaim
      name: influxdb2
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "2Gi"
  - target:
      kind: Deployment
      name: influxdb2
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "200Mi"
  - target:
      kind: Ingress
      name: influx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: telemetry.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: telemetry.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-telemetry.test.b4mad.racing
  - target:
      kind: Ingress
      name: paddock
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: paddock.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: paddock.test.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-paddock.test.b4mad.racing
images:
  - name: paddock
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing-test/paddock
    newTag: latest
