apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: humans
    app.kubernetes.io/name: b4mad-racing-test
    app.kubernetes.io/version: v0.1.0-dev
namespace: b4mad-racing-test
resources:
- namespace.yaml
- postgresql
- influx
- mosquitto
- paddock
