{
 "title": "InfluxDB",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instanceInfluxDB",
    "query": {
     "query": "label_values(influxdb_uptime_seconds,instance)"
    }
   },
   { "name": "jobInfluxDB", "query": "b4mad-racing-influxdb2" }
  ]
 },
 "panels": [
  {
   "title": "Influx Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of total buckets on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_buckets_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of total dashboards on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_dashboards_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of total organizations on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_organizations_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of total scrapers on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_scrapers_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of total tokens on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_tokens_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "influxdb process uptime in seconds",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_uptime_seconds{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of total users on the server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_users_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of calls",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "service_onboard_new_call_total{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Number of tasks currently being executed",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_current_execution{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "Tasks"
      }
     ]
    },
    {
     "title": "Duration of calls buckets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "service_bucket_new_duration_bucket{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Duration of calls onboarding",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "service_onboard_new_duration_bucket{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Percent of the promise queue that is currently full",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "task_executor_promise_queue_usage{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "Queues Full"
      }
     ]
    },
    {
     "title": "Percent of the promise queue that is currently full",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "task_executor_promise_queue_usage{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "Queues Full"
      }
     ]
    },
    {
     "title": "Percent of total available workers that are currently busy",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_executor_workers_busy{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Total number of times an execution has failed",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 7, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_total_execute_failure{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Total number of executions across all tasks",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_total_execution_calls{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Total number of executions across all tasks",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_total_release_calls{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Total number of schedule requests",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_total_schedule_calls{instance=\"$instanceInfluxDB\"}"
      }
     ]
    },
    {
     "title": "Total number of schedule requests that fail to schedule",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "task_scheduler_total_schedule_fails{instance=\"$instanceInfluxDB\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request for InfluxDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "http_api_request_duration_seconds_bucket{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "{{user_agent}}"
      }
     ]
    },
    {
     "title": "Request Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 34 },
     "targets": [
      {
       "expr": "http_api_requests_total{instance=\"$instanceInfluxDB\"}",
       "legendFormat": "{{user_agent}}"
      }
     ]
    }
   ]
  },
  { "title": "GO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Duration of garbage collection cycles.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    },
    {
     "expr": "go_gc_duration_seconds_count{instance=\"influxdb:8086\", job=\"influxdb\"}"
    }
   ]
  },
  {
   "title": "Number of goroutines that currently exist",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    }
   ]
  },
  {
   "title": "Number of bytes allocated and still in use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    }
   ]
  },
  {
   "title": "Number of bytes used by the profiling bucket hash table",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes allocated, even if freed.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    }
   ]
  },
  {
   "title": "fraction  CPU time used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=\"$instanceInfluxDB\", job=\"$jobInfluxDB\"}"
    }
   ]
  }
 ]
}