[agent]
collection_jitter = "0s"
debug = true
flush_interval = "2s"
flush_jitter = "0s"
hostname = "$HOSTNAME"
interval = "1s"
logfile = ""
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
quiet = false
round_interval = true

[[processors.enum]]
[[processors.enum.mapping]]
dest = "status_code"
field = "status"

[processors.enum.mapping.value_mappings]
critical = 3
healthy = 1
problem = 2

[[outputs.influxdb_v2]]
bucket = "racing"
organization = "b4mad"
token = "KHxFBLKlcfv3"
urls = [
  "http://b4mad-racing-influxdb2.b4mad-racing.svc.cluster.local:8086",
]

[[inputs.statsd]]
allowed_pending_messages = 10000
metric_separator = "_"
percentile_limit = 1000
percentiles = [
  50.0,
  95.0,
  99.0,
]
service_address = ":8125"

# SimHub
[[inputs.mqtt_consumer]]
data_format = "json_v2"
password = "admin"
servers = ["tcp://mosquitto-tcp.b4mad-racing.svc.cluster.local:1883"]
topics = [
  "racing/#",
]
username = "admin"

[[inputs.mqtt_consumer.topic_parsing]]
topic = "racing/+/+/+/+/+/+/+"
# measurement = "measurement/_"
tags = "_/user/UserId/SessionId/GameName/TrackCode/CarModel/SessionTypeName"
# fields = "_/_/_/test"

[inputs.mqtt_consumer.topic_parsing.types]
CarModel = "string"
GameName = "string"
SessionId = "string"
TrackCode = "string"
UserId = "string"
user = "string"

[[inputs.mqtt_consumer.json_v2]]
measurement_name = "laps"
timestamp_format = "unix_ms"
timestamp_path = "time"
timestamp_timezone = "UTC"

# [[inputs.mqtt_consumer.json_v2.tag]]
# path = "userId"
# type = "text"

# [[inputs.mqtt_consumer.json_v2.field]]
# path = "carState.CarCoordinates.0"
# rename = "world_x"

[[inputs.mqtt_consumer.json_v2.object]]
disable_prepend_keys = true
path = "telemetry"
timestamp_key = "time"
# excluded_keys = ["CarCoordinates"]
# tags = ["CarModel", "CarClass"]

# CrewChief
[[inputs.mqtt_consumer]]
servers = ["tcp://mosquitto-tcp.b4mad-racing.svc.cluster.local:1883"]
topics = [
  "crewchief/#"
]
username = "admin"
password = "admin"
data_format = "json_v2"

[[inputs.mqtt_consumer.topic_parsing]]
topic = "crewchief/+/+/+/+/+/+/+"
tags = "_/user/UserId/SessionId/GameName/TrackCode/CarModel/SessionTypeName"
[inputs.mqtt_consumer.topic_parsing.types]
user = "string"
UserId = "string"
SessionId = "string"
GameName = "string"
TrackCode = "string"
CarModel = "string"
SessionTypeName = "string"

[[inputs.mqtt_consumer.json_v2]]
measurement_name = "laps_cc"
timestamp_path = "time"
timestamp_format = "unix_ms"
timestamp_timezone = "UTC"

[[inputs.mqtt_consumer.json_v2.object]]
path = "telemetry"
timestamp_key = "time"
disable_prepend_keys = true
