apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: on-pullrequest
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, buildah, .tekton/tasks/e2e-telemetry-test.yaml, .tekton/tasks/unit-pytest.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"

spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  taskRunSpecs:
    - pipelineTaskName: build
      taskServiceAccountName: pipelines-sa-userid-1000
    - pipelineTaskName: push-to-quay
      taskServiceAccountName: pipelines-sa-userid-1000
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)

      - name: e2e-tests
        runAfter:
          - fetch-repository
        taskRef:
          name: e2e-telemetry-test
        workspaces:
          - name: source
            workspace: source

      - name: unit-tests
        runAfter:
          - fetch-repository
        taskRef:
          name: unit-pytest
        workspaces:
          - name: source
            workspace: source

      - name: build
        taskRef:
          name: buildah-as-userid-1000
          kind: ClusterTask
        runAfter:
          - e2e-tests
          - unit-tests
        params:
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/paddock:$(params.revision)
          - name: BUILDER_IMAGE
            value: registry.access.redhat.com/ubi9/buildah@sha256:8b1144b8534507a4b7e71d11174b483c373906828fca669978a3aa63b63af6e3
          - name: DOCKERFILE
            value: Containerfile
          - name: CONTEXT
            value: components/paddock
        workspaces:
          - name: source
            workspace: source

      - name: push-to-quay
        taskRef:
          kind: ClusterTask
          name: skopeo-copy
        runAfter:
          - build
        params:
          - name: srcImageURL
            value: docker://image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/paddock:$(params.revision)
          - name: destImageURL
            value: docker://quay.io/b4mad/paddock:$(params.revision)
          - name: srcTLSverify
            value: "false"
          - name: destTLSverify
            value: "false"
        workspaces:
          - name: images-url
            workspace: images-url

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: images-url
      emptyDir: {}
