---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: telemetry
  creationTimestamp: null
  annotations:
    kubernetes.io/tls-acme: "true"
    haproxy.router.openshift.io/timeout: 15m
spec:
  host: telemetry.b4mad.racing
  to:
    kind: Service
    name: influxdb2
    weight: 100
  tls:
    termination:                   edge      
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http
  wildcardPolicy: None
