kind: Secret
apiVersion: v1
metadata:
    name: paddock-settings
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:OIuvKOfGv7eJ+FiMHLDqreqK9YJ0/S4Gt24DGl4IZwld2oxOZGDDLA==,iv:672ny0yFOVGYR2MG/RIAN5XQLYFRIY5IpJ17l5+5UkU=,tag:04g1eFfBrbniqxaNRkeQGw==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:1VF/dBHL5kXY3MOANDjQT/cOxco=,iv:rSGQtzQ5hl1rehO/MMrB2bSZBT+cbLV8BOxkhZNhRR8=,tag:UH0t68U9WtucXraiCKeEbw==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:HaPxQgQAY1Boi98cVUTK6UE=,iv:gvFmRGXTBx78gqYKHO+mb5+vWXyxQvm4vIEVDl+Z7VE=,tag:zcJetfb+q5R3nTovvxqLvw==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:1zyzVgE=,iv:chE+jpahZUYB5samQByVIq9K/8r/FeifXdKpuG0aciI=,tag:8ajTippBEz/eD80tA6PQZg==,type:str]
    B4MAD_RACING_MQTT_USER: ENC[AES256_GCM,data:ibUmf+3dUo4X,iv:zHl0Rb+WjYmgTWan/0lc7so1fHDHyi48kh/WQYmJjtQ=,tag:IAAPcJMimqge5T3iVweMcg==,type:str]
    B4MAD_RACING_MQTT_PASSWORD: ENC[AES256_GCM,data:EZYcGj84k0O6,iv:KrWZEhsCGm5Aia7hoilvMGw/3LhfbJ5NNoBiGy1uEEY=,tag:bFAJ6MW2DqOMBv/RFitttQ==,type:str]
    B4MAD_RACING_MQTT_HOST: ENC[AES256_GCM,data:LGMvllTvLMY6l+EbDKU=,iv:mO7yrVXAjhcNkbD0o0ZC45SSuT9QJyAeibEACzf3Go4=,tag:pboXnyQjW9lYEwg7WhzTTA==,type:str]
    B4MAD_RACING_MQTT_PORT: ENC[AES256_GCM,data:1NckAw==,iv:qzKrGC8i7fiveE1pdyS03Aqn7MVCkvz6jDoTxW7Dcuo=,tag:fFxAA51C0O1NI8GAH7TuqQ==,type:str]
    B4MAD_RACING_INFLUX_ORG: ENC[AES256_GCM,data:dlcymLM=,iv:4tJsUkD6nXzvvRO7NqZEidTEjzhvr4ERY1r88OhMffk=,tag:/IIwK7Og7f0cdXl16ze9UA==,type:str]
    B4MAD_RACING_INFLUX_TOKEN: ENC[AES256_GCM,data:p65bFkKIUd4z/UUol02N49jpVd0=,iv:8Wiox3EoBNFxateL3fj6th15nuX5OLtoGuBHpXWQKUs=,tag:jmKK/ind2DguTypx5vMX+g==,type:str]
    B4MAD_RACING_INFLUX_URL: ENC[AES256_GCM,data:kLm1Sr6oWH5EqAtx9i5EGcWXirwURBhwXZ5JH0g9UIsX683XqCgTL6WXbKpFDl1EiX9zO6I=,iv:t0R7c8JucG/jYIqjl9FPnYqVEc3BVuHoFRhnEvf75VM=,tag:IpTlc+2O9BITD4JdphMgpg==,type:str]
    READONLY_DATABASE_URL: ENC[AES256_GCM,data:xJiO++V/JI4lNK1vxBm9Cjkenrqo0FtjYDmlDH4a1wUpV6oE8nTRXoEsgjI2bc+I0kecFc5dX3raoHloc3sRvbQ4+K5wJ0/kTwZ57gmCjx1COR6IquEEr/d5uQ==,iv:NbuSXlprxqk1Md6bXAfq2CmxhhulyrQ8ZLnvnKr5tB8=,tag:hqYnsPx8QW4f6oFEas3nsw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:VFZetbPKLtcuwNi1Pdxu1tC+LxC+z10u6qDBWGbKhvqhgSnhU1NauL0lZuYFUdt7Sx8eJ9eLn+ceSIIJQTWcpxSUizQmbW3/yVWDsF7akFwQVQqFr3ERwxvCTAw=,iv:CxW0faeGSN5te7UyLvlVVX5D/gf1xVUClRhsSfAnpXY=,tag:pPVLmxTf9gMQo27paCYY0A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-17T07:00:31Z"
    mac: ENC[AES256_GCM,data:HOpEqocCFuBdFgUGBsSqukkqVuENYG3s1GoBIk7h/MBY+njIvjDU+roa8xS0SYpl5azW4+jRBeJnM4TzztDQhi1yiTQOK2zk9fPP+/4bxPDw2xfPQqRJ3RtXwYaiOXEo4d1gFZm4LLtt/ZmNJWeW3aqbV8jG75VxuGyEFFZdoyE=,iv:B9QpX6OUSDGebWZAJWc9h9eM1y8+XR10r8G35u8/21o=,tag:4GfgvG7UufqIH6ENY8G1mA==,type:str]
    pgp:
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAArPFbc27LcUeJdSvYg4BjuTyOQODQFf9HwGvSY5rHLWCN
            9xHwlMlT4wSi3uXWvMSH97zq9fei4SgGkgur9Bj0wF2CvZFH2mQcft+uSUoGVrHG
            EUCAXpVPQZT5Bkq4TaGguJad63ljJZSRb3CU13niPlr7wBtkGRjY2yS0jmil/nf2
            D0eiUippz5qBzoUlrK3LQ7yJniQ+xbDVr/1PbaCB2B5l8D1o+6NVZMV2IOrkLg+r
            8MK93F4YCXgvLjxxqsfkHNEWI974tvqLOE5WNMieQWWUgjDpDQMfX/hZ+JZS7mSi
            CmeozIWsgMkWQuR2NhGloVTc6OfJ+WvT/jPQ+qkhAqegmww71XodjoSLinfSkC9H
            v5qh+GyBrGjXZZN72MP3M0ebCVw2Pqq/6hS0FXGkeHPxosDGSHlPcJr+9hrY0Qnr
            iS6pAdaw4Tm54DndCIO9OLtqMxZYEX8ttU3mGdd9NEoENnnBuwU85AaRo+r4QaLs
            N2wLGedmDZa+p6MxObFVq+34RB0f7h3GjCpSX6evqVQVthu8R1iDrQBhUHCPHVZG
            7fy1jH3Tm+8AeZp3e5YBC2zMYDYkmMkYjHGTvZwlW5SVQ4J03aOMzd+QWvWmQwuH
            FzlxHGe1MQXyClBTFmC254+lRS95t5xDrsIgi1bFpCandZQYQFUDkeLLxBoxaKDS
            XgHUe2+5pWvMz3Lt3DalV4fJ50E94krPUUY5Tho6S1WI0K5HADBAzMJErA7zwnZ/
            YrjPihMDyZLN538cr6CJn93FqSYXRbGz84xlaIq4cBEGk9D/PjZaDLc4gnptZ9E=
            =Dugu
            -----END PGP MESSAGE-----
          fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQgAkBGMTyu+ex7BR4uPWSbd8Ssn++tXgcQZmUxqcK8VMq+y
            SW7nHNY/qm/F6aHfPrDsMS2+adEyazMTD85sfgRt1g6jzIvkBsLgNorAHNjITjah
            J79oo8qm81EmqA0R345IptsVSXPpDCTkQeCOGrFFehvcqIk1P/ZabOchEBy5ngSP
            LJCxXRWZ9XQaxuDr5HJGLh+dg3q5BHy65GWHfO1x/f+R607hAoDgU3+fjepwPmn3
            n6/Y0+kEIhHwhNo/YroMxMlEyYNWNL1p3CGlU6IpgC2ojJEAeRWcJk9FmbhwBqm0
            K1He47L0m5+exhc18tt4D7az5BKMRDXLYyW3DqhZ79JeAbuRtS829CZY56dndZpo
            HCKYBe4e8YtqPZ/OBjkUympagRhGhLbgk8kiafh9cbAe9r3KFtqRCM4eNB11z8E1
            UAzzh5/5VD+2MxNi2i3JVPtFMJJ5Cz4VrfqLEx+8bw==
            =rObV
            -----END PGP MESSAGE-----
          fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf5Ab03Dpq0bgKF8/7V694Ebu1pjyg9WukD2gbWmjt8YGk1
            BP+oyES8b7xbahgP9gPhScQHvqWCuYWQVas70lCsSH4kzV3MQbSsGujU76WtUjzY
            CW5wKblX24aqo/8z47ZJtfdkhm5YAXxo/5Engcgn/8yd9ZObyrDeFHnnDwxHfeyQ
            o0Sc5yhRVhtpiqjW3K5Q5vLW/a+K/TECpCQSB65YfaN3Hi+GwB9bxe5qLomacK/f
            afrbmJMwKuyjKxhkSS1y0aCO/b9fkraGWpqAy9TUnsx0vyO6eQxe7/629GefP+ku
            BeGXQSEFYtRImaM6DO5eIgVfkLbwguJeXwRKy6QWn9JeAXsYs7WXrj/uBVshcI8M
            TLrmlixDElaNoF6o7V5tPFVJYmGmKfJspMk+4xtdWWGHkfTKqOG3QaRzjjUozMvd
            HhxSi/X10DY6nuRf7H8KDIwkOaUszHf/F8l5GjfoSQ==
            =6FPY
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ/+OftX0hUn1Y1faN7RieqWBDXmst6asiIMUJL8+u742ST6
            2emmvXROzEnVIHM4pR99jzbJ5Op/SaO8UEzGh/fx4dgJnS+2hO4WlrlJ+1oFGD5s
            qZRoy7D8t2Q+QMMrxslakG32dQmckWuq9Mjx9PGDlDeLH7fVr6RUD1vs/tsuBIO9
            BlXfnD8LOtGgIA84mOScgF9V9xx928pMq+nk0LcOb1rfEJ9RZjWMn3R5BlfDvrvs
            ZR93abntyiA8Ye/cS178uwbt9yTm+21ag/30/1kk6DeSkoLivLAjTM5MEcCHvcaZ
            zteGShGLspx0nWNx8LS2FJxWb/5Ii6+lQjX/E7YWGg6v0GNIvNx5TV2V+FLfZ69m
            M3NRmjJapyEZlRtJ1snBPGZpSu0I0wuuaDzB2EAhcm+YHxRgNa1MV2nnZrQl5Una
            XRqiISJTEiW5qK9MG13pzX6zORdUcKQBgcHj1MfGWE4WDdlRgfCrHixsTz7EshGK
            Ih166XjklBNbX+lWAW1sklp4lHByRUintOFz8eZuNHwCad3NTAwx/tSu/KCkgWWP
            /7xGLoUhvNxzPt7BhsijF9gO1pL0brHKqK5i1XlygltPAAQYZzOeqEL5oQQoW2RS
            wmAwLsj2zzTjz1M1TECHVhTHhFVet5ugK/kxK1mBxc0cNpX79ZNLIWJnyBRlv6LS
            XgFEoljpDayw1c19fVEcNBoVtVGeJEiL3TkQ6rvTcPB2jiUbvx3qyILlxrq7MkVz
            /cMnBCPgGAec0aY/UdftdtL/LKCALTtnVwc5UDKVf2mHLqm3nOuEsYuxOrCfuIA=
            =CmXx
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.2
