apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgo-reader
  namespace: b4mad-racing
spec:
  encryptedData:
    password: AgAuCxI8VqiwKv44n+tG4q6RNGbI2rOKWLY1zvfNw3dB9438rH7okWlP6Sax0JeMUagyncrNOE4dtPX73HWL95nqOyAmbOiiYbSJrnM+mXfjbho+ISYcb9BgqbHxekdbbWQoj5SRPRarZ49K0H80V8cIKEaNVApcuGLcceKv51iLyAm5PrMRMZh7q5RdJnDNzvyZkdoD7rkvgj5Uh4XiFOc1sT6ePtfDkclqs/hGU0/UUCG4aBDZ4u1ihyYSMSN111v7Gl6Sp5xZd4/ATu4JsNt+SUDWlJhf0n3JXKu3fKvwUVtorc7kVcCRIoT1AnWJ3WmqfH45Y8TFxoPIidqHTcGLP9bmoO3T+qirS9H+4JznfP3ttG6s2Q8g94rh+5+T6QO7GkkYCedL9+iWlCJkOPQ7RLzdnA6V++ki3zLN+8zhdIjDbjNkUyviEV60pu4mfoA7mWIFsIQrsLsGRR/Gqv5AukD0lvynOGzH7UGb2Hc/foXul7lSUcLSjkL0Kht+TeE3l4s4uylBXXddARwxrnyxGMiq1P8MOMzCal23qPsMw0M57675VhWCYk8uFw8vp4ldV6cvsAoE8K1NV5KYh9k+W8wgshUGoztbfdCOdPa5lJpYCMZh1LWTJPwbwZQCYHtt+YimkVBbS7nYjQCs/FyEcvdGO/EpAlKfsvMO/gAMH06M4luXOAbKJO+4zYUKxf3E2ycgFm3H6sZnAFq+/LXswLlXmg==
    user: AgCRReco+8OeyOEXqzonbZIZiea0P9sYx1PlcwL6bwFs1vMyMcQB0pQvMZAkSMRscFbd8YZYBbbKw7A8uaK9UizD/lx/B2/oEgP3FlK5mXM+t4Kw+GMMkheS9W6fyd1fILCezog3ZzH80hqnxl0JZGs/TufYK7lvnEfjXyzi7ITkq7WWC6vyiLmE72Xztgagd8AWQeU36a19pYm9NMbi+V1QJheiiKfwhDflneaY3rCm7gyHTvTLhet79Ok7mAJypQbLfomdUNDrF42RQHAr9BYsG1C7JTPIqR9CdfgdB5YcgM2qtBHbLcjLpeX8ZXiBXh+aTQiE6uhqRl/OTsEzRkTrYyj5v/uzJDIzUrRhl3FF3oABpxqwqtPhKm90f3Fz6jwpLNkzaIDzOq/Hsqr40WXmbkmH9jDUOOVud9AXmCocD1PoKZxpeBFb/QGLuA6uis5DOms6K3oa5qw5p6rXm3W1JNlMSEdbgQbP6uZ9vWgt2gecGuzzubMHn0yc4o9d9vXqG5DxXDy1zrss7X289WH0BPO0l5IZu0eQtlOs/+vPkf83LVQYturzyrcvSytfuKJQo7T/grSb+IpPx6B2qLfBDWry08BTzZAqFUmf+y0wyOcJebf3z2Uiy3zf0uXzRqulG7X/zkJBj3Y0dbiKDw/S6x8bPUNcj39MpBrZ/s7PE451w+hA7Lqxxft0Ai3l28QEgXPnYsQ=
  template:
    metadata:
      creationTimestamp: null
      name: pgo-reader
      namespace: b4mad-racing
    type: Opaque
