# Generated by Django 5.0 on 2023-12-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Copilot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("description", models.CharField(max_length=255)),
                ("published_at", models.DateTimeField(verbose_name="publishing date")),
                ("updated_at", models.DateTimeField(verbose_name="last update")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(default=None)),
                ("mqtt_drivername", models.CharField(blank=True, default="", max_length=64, null=True)),
                ("initial_transport_test_passed", models.BooleanField(default=False)),
                ("publicly_visible", models.BooleanField(default=True)),
                ("newsletter_allowed", models.BooleanField(default=True)),
                ("subscriptions", models.ManyToManyField(blank=True, to="b4mad_racing_website.copilot")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
