# Generated by Django 5.0 on 2023-12-15 21:15

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b4mad_racing_website", "0002_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopilotInstance",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("DISABLED", "Disabled"),
                            ("MISCONFIGURED", "Misconfigured"),
                            ("CONFIGURED", "Configured"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                        ],
                        default="MISCONFIGURED",
                        max_length=13,
                    ),
                ),
                (
                    "copilot",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="b4mad_racing_website.copilot",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="b4mad_racing_website.profile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
