# Generated by Django 4.2.8 on 2023-12-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0025_alter_coach_mode"),
        ("b4mad_racing_website", "0003_copilotinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="driver",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="telemetry.driver"
            ),
        ),
        migrations.AlterField(
            model_name="copilotinstance",
            name="copilot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="b4mad_racing_website.copilot",
            ),
        ),
    ]
