# Generated by Django 4.2.8 on 2023-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b4mad_racing_website", "0005_copilot_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="copilot",
            name="slug",
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
