apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/paddock
  - ../../../base/paddock/paddock-settings
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: paddock
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 6Gi
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/memory
        value: 2Gi
