apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-password
stringData:
    passwords: ENC[AES256_GCM,data:14zJMYbVjDUb0mB2IeVuP6uFoVkQ3FfMa/aF/feUDvVuMqfY07I7TioIQ0gRgpZVtsnchp9gRp9zJC2zkggFkT1JgR9ZpnEHAj09/KWqi6UOJ8lV2gt+pw6lCmHhgWPFYzGMoNHTNGBe6ju8TEpZjT1ZA+bG6ugMq5eX3U34NnhzRKxTeMd4UWJWYQKPGGBmNebT9UAHcgX9zq5OSEVjKEPlQCrPME1nVQyyAF/6VYLaWZLmZJm/XFeE3uIjK0u1d2N+Cu5iBjwj70+B/vBlNpFk8MQtmACD6M6QsvfLkuby4hpb4C2RorJWsCXdfW0CwHCFvaHBFQzYKhUpzp4PRwGWsowlPgvrsmAAx90isRfSajalEk7J6MfZskBUrbqxj80QIpgcyoD7QUXz5JE2Pg6Lv273vsHBS2pqZLOqKwUN0SCitvb2NG5q0OfYrBUODoCRPZT7IeryLM9QL7qZTf7ckyomgH8Tr/or,iv:oIDTuIKDYSz+a2//JVoFaokR8sT9CH+e8oUB4teiGTk=,tag:wvNAH3fNdFalQ6xG6JrHnw==,type:str]
    crewchief-username: ENC[AES256_GCM,data:bDkNLd/CbIF2,iv:c/fParKBdy/89vqaEI0ymlqkT6z0jz3cxF3yCyoyzFQ=,tag:AcYsHE8BRbySMed5wDxCsg==,type:str]
    crewchief-password: ENC[AES256_GCM,data:Ms2mGhzHdfka,iv:wiFNiQRPPLcTDidt9ya6hBrtDll8h6/SvqLDWR9Ipkw=,tag:c8F5Ou/rdbBj5TMUwHcdOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-19T07:13:22Z"
    mac: ENC[AES256_GCM,data:NMSVEDLvqH5wXOdhp27SFJuQiSBbauu5R06b+QG0/6bfCbdlmla1lvyGlIYD3yBviUybT+CRsnNycTgLiVSsx1KYq6gw7B+7cuSyB6qndhWl3aClthrKeGLszIsRO1haH0tV1EZi7kRVIeuVT85oygNj8QqhJJe/9JnuG/eX1AY=,iv:DbCsgPNSaxbRn1fRfdl7zi3TJQdJAaWldTHU4hw85mA=,tag:YVWglSvgII+yrL/0tbWIOw==,type:str]
    pgp:
        - created_at: "2023-09-19T07:13:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+XrDaMvM3KsAQ//bvNgS1KRHEIubnWvEcr4gzH0VKnezWUmpHFZa2IdT5qD
            66sSH4uAHfqzdk7Vbe6/2cEYUtqYxgikut52dEf5GRpg4U+U1XRTF+8NML9WQJyP
            d8U1xxp2OSzIMJvJ55l0rIq6O0duuovgeCyFjDvCc2Cj7xk93Lmn6ytM93YTC2Vv
            1AbaKwMCj3Z42yjYiuoZPZP6CRcIW2jvqw/GTW3/qPY+oLQE0pso1cqSKrkGqRaa
            fhU/MQKXntMLiO5SpeDbLPIJO2Z0CC0KsZSMF9r3pX52M67F+YfgfMYoVrVoMqCP
            Hqt1R5TaYdlyaA1f7GyBRYAdnJ2H5JF7RGFiaqPFWDIFZsuDwMe+GH3FjQ296gE7
            UVKVY8z+jj1B/1NXDhVatyl4FjoAyCCNY5NHI4vh3Gs+eMYzBRRSWr9QBBcqhPCm
            lNSyOeNdeaOeu17pJmEf5GcVWlkaEbJ0GnodP21TIDAwhfl10TbNso5n31vunxO5
            Th3mvvk2EoCtNOsmaBUbmoXiDcou6ArtqrqCJ/Hp/vuGQ4Oaai5KKbAHtQdpqUWK
            ASH94NQ2noKly7yaARpZR+5BuTAMzdcS+PSHGhLhghaZmK82e4pr87u5Cf9EhROq
            HfiJXXUGVPEo8SrOXszNt7C4MXH5jKsG+8zbHmQ0zwMB1dm6FMHzPFuBT8i4HbHS
            XAHkINLx7tb9DV/0fppwN+u+6JespLIcaY20rVYwQqO6zNIlVSNaDFZDpyrB8W8t
            Y4JTiGhtGquajHysvaZyyXQVPq+QblfV80n+TESHDT1xrda7l6UXPeJf9VYw
            =ULwq
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2023-09-19T07:13:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/+PPF4ype05onLWUKX/rVznR35NyFzWsGIA6geIOsbCShN
            Mt3CQQKJnu4AYrGZFR7F0qqX/WmTn0IBWyrmKu7yvaYPe6q9QhiWx8qZS9PGF8gh
            YKQVBy+fr/fykTpWZkH+KMa9GfBLBeH6PtGEUVZqIdY4fHC8dwu7B6zgEPFqc8mk
            eh9cViX7zCAsTjDLwhIJDRJ40Y+Ry8c4Cat0vBwAO1a/RvuPBrfPwX2G8HvJY0dO
            e8OwgAtdurdTlE5BboPGav1AjLyYmFsiMAQ+L7ruMn9TFVOBaJLVGIEgFs6BUx6j
            HpjTLOYDFL051eCZk0DQZ/1Tj7nhaBOgZtWFp2JdfS8+ti9ZeFXVD/tzo3o+6Tby
            G+ilI9Kh+fFM8xE9zWC938sZi3SIMfVLxOznuwBOHc+tgRTr8VQBy38pmTuD3ARx
            DWpOzQHNVs3v9Ut6J4TnCOFX+D2EzRVchMQKbSH3qtTal5gpujPXAx0rhSjZMeMD
            oBJTur4M6RnhVIk9eBcmpmv5vmHbip166XozKQqdG7/EZcRV/+chIATKX3OTDEQo
            SZFV/s2cIpkQYGf51M/7gBOPn4ZLERj0msi+zAE1GBb9inpy/dSXazQQdIjHl1vq
            8ZT0eFECNE3bFhE8Jpmfk9y6klfacmt0cVPXBSU/cdtInAL31/ALKjHp7od74+fS
            XAGPyvRZtG+U31np5nQdUSdnJ0xw+o69CklYC4vpNC96LuTaIhikc1iyuPkHfl4U
            AQXFdy518r1cZgEPV6uTneTVIs/BogKamn/8mIy41+Bg0KyCa6Y/sLfFUiR8
            =txk+
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.8.0-rc.1
